export enum ActionTypes {
  FETCH_CARDS_START = 'FETCH_CARDS_START',
  FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS',
  FETCH_CARDS_ERROR = 'FETCH_CARDS_ERROR',

  CLEAR_CARDS = 'CLEAR_CARDS',
  CLEAR_CARD = 'CLEAR_CARD',

  FETCH_CARD_START = 'FETCH_CARD_START',
  FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS',
  FETCH_CARD_ERROR = 'FETCH_CARD_ERROR',

  DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS',
  DELETE_CARD_ERROR = 'DELETE_CARD_ERROR',

  EDIT_CARD_SUCCESS = 'EDIT_CARD_SUCCESS',
  EDIT_CARD_ERROR = 'EDIT_CARD_ERROR',

  SEARCH_CARDS = 'SEARCH_CARDS',
}
